INSERT INTO ACT_RU_FILTER(ID_, REV_, RESOURCE_TYPE_, NAME_, OWNER_, QUERY_, PROPERTIES_) VALUES
('8bab5d7b-3c4d-11e5-87de-28cfe91731d7', 1, 'Task', 'All Tasks', NULL, '{}', '{"color":"#EEEEEE","priority":0,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('b2f5322d-3c4d-11e5-87de-28cfe91731d7', 2, 'Task', 'Ines', NULL, '{"candidateUser":"Ines","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":1,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"},{"name":"kundenstatus","label":"Kundenstatus"}]}'),
('d6f5f65f-3c4d-11e5-87de-28cfe91731d7', 2, 'Task', 'Herbert', NULL, '{"candidateUser":"Herbert","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":2,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"},{"name":"kundenstatus","label":"Kundenstatus"}]}'),
('417af1c3-3c4e-11e5-87de-28cfe91731d7', 1, 'Task', 'Emma', NULL, '{"candidateUser":"Emma","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":4,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('6f18f415-3c4e-11e5-87de-28cfe91731d7', 1, 'Task', 'Sonja', NULL, '{"candidateUser":"Sonja","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":5,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('b9db231a-3c4e-11e5-87de-28cfe91731d7', 1, 'Task', 'Hanna', NULL, '{"candidateUser":"Hanna","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":7,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('d919a44c-3c4e-11e5-87de-28cfe91731d7', 1, 'Task', 'Bernd', NULL, '{"candidateUser":"Bernd","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":8,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('95ccca57-3c4e-11e5-87de-28cfe91731d7', 2, 'Task', 'Xaver', NULL, '{"candidateUser":"Xaver","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":6,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('ffe03f3e-3c4e-11e5-87de-28cfe91731d7', 1, 'Task', 'Tom', NULL, '{"candidateUser":"Tom","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":9,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}'),
('1f5a8651-3c4e-11e5-87de-28cfe91731d7', 2, 'Task', 'Andreas', NULL, '{"candidateUser":"Andreas","includeAssignedTasks":true}', '{"color":"#b3b3b3","priority":3,"showUndefinedVariable":false,"refresh":true,"variables":[{"name":"vsnr","label":"Versicherungsnummer"}]}');
